# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform VersaTiles installation tasks
  when: versatiles_enabled | bool
  tags:
    - setup-all
    - setup-versatiles
    - install-all
    - install-versatiles
  block:
    - name: Validate VersaTiles configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install VersaTiles
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform VersaTiles uninstallation tasks
  when: not versatiles_enabled | bool
  tags:
    - setup-all
    - setup-versatiles
  block:
    - name: Uninstall VersaTiles
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
