# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of VersaTiles systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ versatiles_identifier }}.service"
  register: versatiles_service_stat

- name: Uninstall VersaTiles systemd services and files
  when: versatiles_service_stat.stat.exists | bool
  block:
    - name: Ensure VersaTiles systemd service is stopped
      ansible.builtin.service:
        name: "{{ versatiles_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure VersaTiles systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ versatiles_identifier }}.service"
        state: absent

    - name: Ensure VersaTiles support files do not exist
      ansible.builtin.file:
        path: "{{ versatiles_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure VersaTiles local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ versatiles_data_path }}"
      register: versatiles_data_path_deletion_result
      changed_when: versatiles_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure VersaTiles base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ versatiles_base_path }}"
      register: versatiles_base_path_deletion_result
      changed_when: versatiles_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure VersaTiles container network does not exist
      when: versatiles_container_network_deletion_enabled
      block:
        - name: Ensure VersaTiles container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ versatiles_container_network }}"
            state: absent
          register: versatiles_network_deletion_result

        - name: Ensure VersaTiles container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ versatiles_container_network }}
          register: versatiles_network_deletion_result
          changed_when: versatiles_container_network in versatiles_network_deletion_result.stdout

- name: Check existence of VersaTiles local data path
  ansible.builtin.stat:
    path: "{{ versatiles_data_path }}"
  register: versatiles_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if VersaTiles local data remains
  when: versatiles_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local VersaTiles instance has been removed, some old data remains in `" + versatiles_data_path + "`. Feel free to delete it."
        ]
      }}
